### PR TITLE
fix: add webpack files to webpack folder (fixes #133)

### LINKED ISSUE #133: refacore: Move all webpack.*.js to .webpack folder
This is cleaner to have `.webpack` or `webpack` folder where all the webpack configs will live. Need to change npm scripts too

### PR DESCRIPTION
**Pull request by Ckbhatia**
fixes #133

### CODE REVIEW

**Comment by Ckbhatia** [comment]
@anikethsaha Please review the changes, Inform me if there is need for any changes

**Review by anikethsaha — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. 

The changes looks good. One note

can we rename the `webpack` folder with `.webpack` . (leading dot)

**Comment by Ckbhatia** [comment]
What is the benefit of that?

**Comment by anikethsaha** [comment]
No benifits in particular, but it states that it contains configurations for the project. 

like `.github` folder

**Comment by Ckbhatia** [comment]
Changes have been made

**Comment by anikethsaha** [comment]
netlify deployement is failing. Can you check that locally if there is any issue with running the scripts.

**Comment by Ckbhatia** [comment]
No, I have verified the changes before pushing. 👍

**Comment by anikethsaha** [comment]
> No, I have verified the changes before pushing. 👍

umm, I will check this soon 👍

**Comment by Ckbhatia** [comment]
Hey,
Did you check?

**Comment by anikethsaha** [comment]
I will check this soon. A bit busy for few coming days

**Comment by Ckbhatia** [comment]
Bro, it's been 8 days. Can you please review now?

**Comment by Ckbhatia** [comment]
@anikethsaha Can you check now?

**Comment by anikethsaha** [comment]
I will check this weekend.

Thank you for your patience

**Comment by Ckbhatia** [comment]
Bro, I think, contributed to a dead project.

**Comment by anikethsaha** [comment]
apologies for delay. 

Did you test locally is there any issue in that ? I didn't check locally, have some issue with my current OS config.

**Comment by Ckbhatia** [comment]
I had checked when I fixed this. It was working fine.

**Pull request merged**
