### PR TITLE
Setup ENZYME for component testing.

### PR DESCRIPTION
**Pull request by przemwierzbicki**
As mentioned, here goes the initial testsuite setup. More to come tomorrow!

### CODE REVIEW

**Comment by anikethsaha** [comment]
Looking good !
Let me resolve some merge conflict in the lock file and then will add this 

Thanks 💯

**Comment by przemwierzbicki** [comment]
Great!

These two dependencies are all that I need to start working on the
testsuite & boilerplate auth.

P.

**Comment by anikethsaha** [comment]
ahh!...I guess something is wrong with installing `coveralls` or something!...no prob ....i will merge this and will take a look at that later!

**Comment by przemwierzbicki** [comment]
Thanks!

I'll get to work right away, and commit some more changes tmrw : ]

P.

**Comment by przemwierzbicki** [comment]
p.s.: Don't worry, if something goes wrong, we'll fix it together, or mb
someone else will :)

**Comment by anikethsaha** [comment]
> I'll get to work right away, and commit some more changes tmrw : ]

Awesome !

> p.s.: Don't worry, if something goes wrong, we'll fix it together, or mb
someone else will :)

Yeah ! sure.

**Comment by anikethsaha** [comment]
@all-contributors please add @przemwierzbicki for infrastructure, tests and code

**Pull request merged**
